# Generated by Django 5.2.16 on 2026-07-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_companies',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='crm.company'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to='crm.company'),
        ),
    ]
