# Generated by Django 5.2.16 on 2026-07-12 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0002_initial'),
        ('projects', '0002_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='sender_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='crm.company'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='sender_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='clientactivity',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='brandasset',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='deliverableversion',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='client_portal.deliverable'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='client_portal.clientmessage'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='onboardingworkflow',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='crm.company'),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='client_portal.onboardingworkflow'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='revisionrequest',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='client_portal.deliverableversion'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_portal.clientuser'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'client_user', 'team_member')},
        ),
    ]
