# Generated by Django 5.2.16 on 2026-07-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='team.organization'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.servicecatalog'),
        ),
    ]
